//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.03 at 09:18:46 AM ACT 
//


package translator.cdxml.dom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}objecttag"/>
 *         &lt;element ref="{}annotation"/>
 *       &lt;/choice>
 *       &lt;attribute name="AngularSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ArrowEquilibriumRatio" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ArrowShaftSpacing" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ArrowheadCenterSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ArrowheadHead">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Unspecified"/>
 *             &lt;enumeration value="None"/>
 *             &lt;enumeration value="Full"/>
 *             &lt;enumeration value="HalfLeft"/>
 *             &lt;enumeration value="HalfRight"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ArrowheadTail">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Unspecified"/>
 *             &lt;enumeration value="None"/>
 *             &lt;enumeration value="Full"/>
 *             &lt;enumeration value="HalfLeft"/>
 *             &lt;enumeration value="HalfRight"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ArrowheadType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Solid"/>
 *             &lt;enumeration value="Hollow"/>
 *             &lt;enumeration value="Angle"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ArrowheadWidth" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BoldWidth" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BoundingBox" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CaptionFace" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CaptionFont" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CaptionSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Center3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Dipole" default="no">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="FadePercent" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FillType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Unspecified"/>
 *             &lt;enumeration value="None"/>
 *             &lt;enumeration value="Solid"/>
 *             &lt;enumeration value="Shaded"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="HashSpacing" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Head3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HeadSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="IgnoreWarnings" default="no">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="LineType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Solid"/>
 *             &lt;enumeration value="Dashed"/>
 *             &lt;enumeration value="Bold"/>
 *             &lt;enumeration value="Wavy"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="LineWidth" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="MajorAxisEnd3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="MinorAxisEnd3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="NoGo">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Unspecified"/>
 *             &lt;enumeration value="None"/>
 *             &lt;enumeration value="Cross"/>
 *             &lt;enumeration value="Hash"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SupersededBy" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Tail3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Visible" default="yes">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Warning" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="bgRGBA" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="fgRGBA" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objecttagOrAnnotation"
})
@XmlRootElement(name = "arrow")
public class Arrow {

    @XmlElements({
        @XmlElement(name = "annotation", type = Annotation.class),
        @XmlElement(name = "objecttag", type = Objecttag.class)
    })
    protected List<Object> objecttagOrAnnotation;
    @XmlAttribute(name = "AngularSize")
    protected String angularSize;
    @XmlAttribute(name = "ArrowEquilibriumRatio")
    protected String arrowEquilibriumRatio;
    @XmlAttribute(name = "ArrowShaftSpacing")
    protected String arrowShaftSpacing;
    @XmlAttribute(name = "ArrowheadCenterSize")
    protected String arrowheadCenterSize;
    @XmlAttribute(name = "ArrowheadHead")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String arrowheadHead;
    @XmlAttribute(name = "ArrowheadTail")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String arrowheadTail;
    @XmlAttribute(name = "ArrowheadType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String arrowheadType;
    @XmlAttribute(name = "ArrowheadWidth")
    protected String arrowheadWidth;
    @XmlAttribute(name = "BoldWidth")
    protected String boldWidth;
    @XmlAttribute(name = "BoundingBox")
    protected String boundingBox;
    @XmlAttribute(name = "CaptionFace")
    protected String captionFace;
    @XmlAttribute(name = "CaptionFont")
    protected String captionFont;
    @XmlAttribute(name = "CaptionSize")
    protected String captionSize;
    @XmlAttribute(name = "Center3D")
    protected String center3D;
    @XmlAttribute(name = "Dipole")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dipole;
    @XmlAttribute(name = "FadePercent")
    protected String fadePercent;
    @XmlAttribute(name = "FillType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fillType;
    @XmlAttribute(name = "HashSpacing")
    protected String hashSpacing;
    @XmlAttribute(name = "Head3D")
    protected String head3D;
    @XmlAttribute(name = "HeadSize")
    protected String headSize;
    @XmlAttribute(name = "IgnoreWarnings")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ignoreWarnings;
    @XmlAttribute(name = "LineType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lineType;
    @XmlAttribute(name = "LineWidth")
    protected String lineWidth;
    @XmlAttribute(name = "MajorAxisEnd3D")
    protected String majorAxisEnd3D;
    @XmlAttribute(name = "MinorAxisEnd3D")
    protected String minorAxisEnd3D;
    @XmlAttribute(name = "NoGo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String noGo;
    @XmlAttribute(name = "SupersededBy")
    protected String supersededBy;
    @XmlAttribute(name = "Tail3D")
    protected String tail3D;
    @XmlAttribute(name = "Visible")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String visible;
    @XmlAttribute(name = "Warning")
    protected String warning;
    @XmlAttribute(name = "Z")
    protected String z;
    @XmlAttribute
    protected String bgRGBA;
    @XmlAttribute
    protected String color;
    @XmlAttribute
    protected String fgRGBA;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the objecttagOrAnnotation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objecttagOrAnnotation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjecttagOrAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Annotation }
     * {@link Objecttag }
     * 
     * 
     */
    public List<Object> getObjecttagOrAnnotation() {
        if (objecttagOrAnnotation == null) {
            objecttagOrAnnotation = new ArrayList<Object>();
        }
        return this.objecttagOrAnnotation;
    }

    /**
     * Gets the value of the angularSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAngularSize() {
        return angularSize;
    }

    /**
     * Sets the value of the angularSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAngularSize(String value) {
        this.angularSize = value;
    }

    /**
     * Gets the value of the arrowEquilibriumRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowEquilibriumRatio() {
        return arrowEquilibriumRatio;
    }

    /**
     * Sets the value of the arrowEquilibriumRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowEquilibriumRatio(String value) {
        this.arrowEquilibriumRatio = value;
    }

    /**
     * Gets the value of the arrowShaftSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowShaftSpacing() {
        return arrowShaftSpacing;
    }

    /**
     * Sets the value of the arrowShaftSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowShaftSpacing(String value) {
        this.arrowShaftSpacing = value;
    }

    /**
     * Gets the value of the arrowheadCenterSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowheadCenterSize() {
        return arrowheadCenterSize;
    }

    /**
     * Sets the value of the arrowheadCenterSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowheadCenterSize(String value) {
        this.arrowheadCenterSize = value;
    }

    /**
     * Gets the value of the arrowheadHead property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowheadHead() {
        return arrowheadHead;
    }

    /**
     * Sets the value of the arrowheadHead property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowheadHead(String value) {
        this.arrowheadHead = value;
    }

    /**
     * Gets the value of the arrowheadTail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowheadTail() {
        return arrowheadTail;
    }

    /**
     * Sets the value of the arrowheadTail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowheadTail(String value) {
        this.arrowheadTail = value;
    }

    /**
     * Gets the value of the arrowheadType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowheadType() {
        return arrowheadType;
    }

    /**
     * Sets the value of the arrowheadType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowheadType(String value) {
        this.arrowheadType = value;
    }

    /**
     * Gets the value of the arrowheadWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowheadWidth() {
        return arrowheadWidth;
    }

    /**
     * Sets the value of the arrowheadWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowheadWidth(String value) {
        this.arrowheadWidth = value;
    }

    /**
     * Gets the value of the boldWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoldWidth() {
        return boldWidth;
    }

    /**
     * Sets the value of the boldWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoldWidth(String value) {
        this.boldWidth = value;
    }

    /**
     * Gets the value of the boundingBox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoundingBox() {
        return boundingBox;
    }

    /**
     * Sets the value of the boundingBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoundingBox(String value) {
        this.boundingBox = value;
    }

    /**
     * Gets the value of the captionFace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptionFace() {
        return captionFace;
    }

    /**
     * Sets the value of the captionFace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptionFace(String value) {
        this.captionFace = value;
    }

    /**
     * Gets the value of the captionFont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptionFont() {
        return captionFont;
    }

    /**
     * Sets the value of the captionFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptionFont(String value) {
        this.captionFont = value;
    }

    /**
     * Gets the value of the captionSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptionSize() {
        return captionSize;
    }

    /**
     * Sets the value of the captionSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptionSize(String value) {
        this.captionSize = value;
    }

    /**
     * Gets the value of the center3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCenter3D() {
        return center3D;
    }

    /**
     * Sets the value of the center3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCenter3D(String value) {
        this.center3D = value;
    }

    /**
     * Gets the value of the dipole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDipole() {
        if (dipole == null) {
            return "no";
        } else {
            return dipole;
        }
    }

    /**
     * Sets the value of the dipole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDipole(String value) {
        this.dipole = value;
    }

    /**
     * Gets the value of the fadePercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFadePercent() {
        return fadePercent;
    }

    /**
     * Sets the value of the fadePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFadePercent(String value) {
        this.fadePercent = value;
    }

    /**
     * Gets the value of the fillType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillType() {
        return fillType;
    }

    /**
     * Sets the value of the fillType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillType(String value) {
        this.fillType = value;
    }

    /**
     * Gets the value of the hashSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHashSpacing() {
        return hashSpacing;
    }

    /**
     * Sets the value of the hashSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHashSpacing(String value) {
        this.hashSpacing = value;
    }

    /**
     * Gets the value of the head3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHead3D() {
        return head3D;
    }

    /**
     * Sets the value of the head3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHead3D(String value) {
        this.head3D = value;
    }

    /**
     * Gets the value of the headSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadSize() {
        return headSize;
    }

    /**
     * Sets the value of the headSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadSize(String value) {
        this.headSize = value;
    }

    /**
     * Gets the value of the ignoreWarnings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIgnoreWarnings() {
        if (ignoreWarnings == null) {
            return "no";
        } else {
            return ignoreWarnings;
        }
    }

    /**
     * Sets the value of the ignoreWarnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIgnoreWarnings(String value) {
        this.ignoreWarnings = value;
    }

    /**
     * Gets the value of the lineType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineType() {
        return lineType;
    }

    /**
     * Sets the value of the lineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineType(String value) {
        this.lineType = value;
    }

    /**
     * Gets the value of the lineWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineWidth() {
        return lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineWidth(String value) {
        this.lineWidth = value;
    }

    /**
     * Gets the value of the majorAxisEnd3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMajorAxisEnd3D() {
        return majorAxisEnd3D;
    }

    /**
     * Sets the value of the majorAxisEnd3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMajorAxisEnd3D(String value) {
        this.majorAxisEnd3D = value;
    }

    /**
     * Gets the value of the minorAxisEnd3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinorAxisEnd3D() {
        return minorAxisEnd3D;
    }

    /**
     * Sets the value of the minorAxisEnd3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinorAxisEnd3D(String value) {
        this.minorAxisEnd3D = value;
    }

    /**
     * Gets the value of the noGo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoGo() {
        return noGo;
    }

    /**
     * Sets the value of the noGo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoGo(String value) {
        this.noGo = value;
    }

    /**
     * Gets the value of the supersededBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupersededBy() {
        return supersededBy;
    }

    /**
     * Sets the value of the supersededBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupersededBy(String value) {
        this.supersededBy = value;
    }

    /**
     * Gets the value of the tail3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTail3D() {
        return tail3D;
    }

    /**
     * Sets the value of the tail3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTail3D(String value) {
        this.tail3D = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisible() {
        if (visible == null) {
            return "yes";
        } else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisible(String value) {
        this.visible = value;
    }

    /**
     * Gets the value of the warning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarning() {
        return warning;
    }

    /**
     * Sets the value of the warning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarning(String value) {
        this.warning = value;
    }

    /**
     * Gets the value of the z property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZ() {
        return z;
    }

    /**
     * Sets the value of the z property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZ(String value) {
        this.z = value;
    }

    /**
     * Gets the value of the bgRGBA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBgRGBA() {
        return bgRGBA;
    }

    /**
     * Sets the value of the bgRGBA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBgRGBA(String value) {
        this.bgRGBA = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the fgRGBA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFgRGBA() {
        return fgRGBA;
    }

    /**
     * Sets the value of the fgRGBA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFgRGBA(String value) {
        this.fgRGBA = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
