//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.03 at 09:18:46 AM ACT 
//


package translator.cdxml.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BasisObjects" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ChemicalPropertyDisplayID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ChemicalPropertyIsActive" default="no">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ChemicalPropertyType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PositioningAngle" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PositioningOffset" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PositioningType" default="auto">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="auto"/>
 *             &lt;enumeration value="angle"/>
 *             &lt;enumeration value="offset"/>
 *             &lt;enumeration value="absolute"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "chemicalproperty")
public class Chemicalproperty {

    @XmlAttribute(name = "BasisObjects")
    protected String basisObjects;
    @XmlAttribute(name = "ChemicalPropertyDisplayID")
    protected String chemicalPropertyDisplayID;
    @XmlAttribute(name = "ChemicalPropertyIsActive")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String chemicalPropertyIsActive;
    @XmlAttribute(name = "ChemicalPropertyType")
    protected String chemicalPropertyType;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "PositioningAngle")
    protected String positioningAngle;
    @XmlAttribute(name = "PositioningOffset")
    protected String positioningOffset;
    @XmlAttribute(name = "PositioningType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String positioningType;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the basisObjects property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasisObjects() {
        return basisObjects;
    }

    /**
     * Sets the value of the basisObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasisObjects(String value) {
        this.basisObjects = value;
    }

    /**
     * Gets the value of the chemicalPropertyDisplayID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChemicalPropertyDisplayID() {
        return chemicalPropertyDisplayID;
    }

    /**
     * Sets the value of the chemicalPropertyDisplayID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChemicalPropertyDisplayID(String value) {
        this.chemicalPropertyDisplayID = value;
    }

    /**
     * Gets the value of the chemicalPropertyIsActive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChemicalPropertyIsActive() {
        if (chemicalPropertyIsActive == null) {
            return "no";
        } else {
            return chemicalPropertyIsActive;
        }
    }

    /**
     * Sets the value of the chemicalPropertyIsActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChemicalPropertyIsActive(String value) {
        this.chemicalPropertyIsActive = value;
    }

    /**
     * Gets the value of the chemicalPropertyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChemicalPropertyType() {
        return chemicalPropertyType;
    }

    /**
     * Sets the value of the chemicalPropertyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChemicalPropertyType(String value) {
        this.chemicalPropertyType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the positioningAngle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositioningAngle() {
        return positioningAngle;
    }

    /**
     * Sets the value of the positioningAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositioningAngle(String value) {
        this.positioningAngle = value;
    }

    /**
     * Gets the value of the positioningOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositioningOffset() {
        return positioningOffset;
    }

    /**
     * Sets the value of the positioningOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositioningOffset(String value) {
        this.positioningOffset = value;
    }

    /**
     * Gets the value of the positioningType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositioningType() {
        if (positioningType == null) {
            return "auto";
        } else {
            return positioningType;
        }
    }

    /**
     * Sets the value of the positioningType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositioningType(String value) {
        this.positioningType = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
