//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.03 at 09:18:46 AM ACT 
//


package translator.cdxml.dom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}objecttag"/>
 *         &lt;element ref="{}annotation"/>
 *       &lt;/choice>
 *       &lt;attribute name="ArrowheadHead">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Unspecified"/>
 *             &lt;enumeration value="None"/>
 *             &lt;enumeration value="Full"/>
 *             &lt;enumeration value="HalfLeft"/>
 *             &lt;enumeration value="HalfRight"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ArrowheadTail">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Unspecified"/>
 *             &lt;enumeration value="None"/>
 *             &lt;enumeration value="Full"/>
 *             &lt;enumeration value="HalfLeft"/>
 *             &lt;enumeration value="HalfRight"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ArrowheadType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Solid"/>
 *             &lt;enumeration value="Hollow"/>
 *             &lt;enumeration value="Angle"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="BoldWidth" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BoundingBox" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Closed" default="no">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CurvePoints" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CurvePoints3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CurveSpacing" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CurveType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FadePercent" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FillType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Unspecified"/>
 *             &lt;enumeration value="None"/>
 *             &lt;enumeration value="Solid"/>
 *             &lt;enumeration value="Shaded"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="HashSpacing" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HeadCenterSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HeadSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HeadWidth" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="IgnoreWarnings" default="no">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="LineType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Solid"/>
 *             &lt;enumeration value="Dashed"/>
 *             &lt;enumeration value="Bold"/>
 *             &lt;enumeration value="Wavy"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="LineWidth" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SupersededBy" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Visible" default="yes">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Warning" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="bgRGBA" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="fgRGBA" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objecttagOrAnnotation"
})
@XmlRootElement(name = "curve")
public class Curve {

    @XmlElements({
        @XmlElement(name = "objecttag", type = Objecttag.class),
        @XmlElement(name = "annotation", type = Annotation.class)
    })
    protected List<Object> objecttagOrAnnotation;
    @XmlAttribute(name = "ArrowheadHead")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String arrowheadHead;
    @XmlAttribute(name = "ArrowheadTail")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String arrowheadTail;
    @XmlAttribute(name = "ArrowheadType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String arrowheadType;
    @XmlAttribute(name = "BoldWidth")
    protected String boldWidth;
    @XmlAttribute(name = "BoundingBox")
    protected String boundingBox;
    @XmlAttribute(name = "Closed")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String closed;
    @XmlAttribute(name = "CurvePoints")
    protected String curvePoints;
    @XmlAttribute(name = "CurvePoints3D")
    protected String curvePoints3D;
    @XmlAttribute(name = "CurveSpacing")
    protected String curveSpacing;
    @XmlAttribute(name = "CurveType")
    protected String curveType;
    @XmlAttribute(name = "FadePercent")
    protected String fadePercent;
    @XmlAttribute(name = "FillType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fillType;
    @XmlAttribute(name = "HashSpacing")
    protected String hashSpacing;
    @XmlAttribute(name = "HeadCenterSize")
    protected String headCenterSize;
    @XmlAttribute(name = "HeadSize")
    protected String headSize;
    @XmlAttribute(name = "HeadWidth")
    protected String headWidth;
    @XmlAttribute(name = "IgnoreWarnings")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ignoreWarnings;
    @XmlAttribute(name = "LineType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lineType;
    @XmlAttribute(name = "LineWidth")
    protected String lineWidth;
    @XmlAttribute(name = "SupersededBy")
    protected String supersededBy;
    @XmlAttribute(name = "Visible")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String visible;
    @XmlAttribute(name = "Warning")
    protected String warning;
    @XmlAttribute(name = "Z")
    protected String z;
    @XmlAttribute
    protected String bgRGBA;
    @XmlAttribute
    protected String color;
    @XmlAttribute
    protected String fgRGBA;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the objecttagOrAnnotation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objecttagOrAnnotation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjecttagOrAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Objecttag }
     * {@link Annotation }
     * 
     * 
     */
    public List<Object> getObjecttagOrAnnotation() {
        if (objecttagOrAnnotation == null) {
            objecttagOrAnnotation = new ArrayList<Object>();
        }
        return this.objecttagOrAnnotation;
    }

    /**
     * Gets the value of the arrowheadHead property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowheadHead() {
        return arrowheadHead;
    }

    /**
     * Sets the value of the arrowheadHead property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowheadHead(String value) {
        this.arrowheadHead = value;
    }

    /**
     * Gets the value of the arrowheadTail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowheadTail() {
        return arrowheadTail;
    }

    /**
     * Sets the value of the arrowheadTail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowheadTail(String value) {
        this.arrowheadTail = value;
    }

    /**
     * Gets the value of the arrowheadType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowheadType() {
        return arrowheadType;
    }

    /**
     * Sets the value of the arrowheadType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowheadType(String value) {
        this.arrowheadType = value;
    }

    /**
     * Gets the value of the boldWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoldWidth() {
        return boldWidth;
    }

    /**
     * Sets the value of the boldWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoldWidth(String value) {
        this.boldWidth = value;
    }

    /**
     * Gets the value of the boundingBox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoundingBox() {
        return boundingBox;
    }

    /**
     * Sets the value of the boundingBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoundingBox(String value) {
        this.boundingBox = value;
    }

    /**
     * Gets the value of the closed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClosed() {
        if (closed == null) {
            return "no";
        } else {
            return closed;
        }
    }

    /**
     * Sets the value of the closed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosed(String value) {
        this.closed = value;
    }

    /**
     * Gets the value of the curvePoints property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurvePoints() {
        return curvePoints;
    }

    /**
     * Sets the value of the curvePoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurvePoints(String value) {
        this.curvePoints = value;
    }

    /**
     * Gets the value of the curvePoints3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurvePoints3D() {
        return curvePoints3D;
    }

    /**
     * Sets the value of the curvePoints3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurvePoints3D(String value) {
        this.curvePoints3D = value;
    }

    /**
     * Gets the value of the curveSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurveSpacing() {
        return curveSpacing;
    }

    /**
     * Sets the value of the curveSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurveSpacing(String value) {
        this.curveSpacing = value;
    }

    /**
     * Gets the value of the curveType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurveType() {
        return curveType;
    }

    /**
     * Sets the value of the curveType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurveType(String value) {
        this.curveType = value;
    }

    /**
     * Gets the value of the fadePercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFadePercent() {
        return fadePercent;
    }

    /**
     * Sets the value of the fadePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFadePercent(String value) {
        this.fadePercent = value;
    }

    /**
     * Gets the value of the fillType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillType() {
        return fillType;
    }

    /**
     * Sets the value of the fillType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillType(String value) {
        this.fillType = value;
    }

    /**
     * Gets the value of the hashSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHashSpacing() {
        return hashSpacing;
    }

    /**
     * Sets the value of the hashSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHashSpacing(String value) {
        this.hashSpacing = value;
    }

    /**
     * Gets the value of the headCenterSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadCenterSize() {
        return headCenterSize;
    }

    /**
     * Sets the value of the headCenterSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadCenterSize(String value) {
        this.headCenterSize = value;
    }

    /**
     * Gets the value of the headSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadSize() {
        return headSize;
    }

    /**
     * Sets the value of the headSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadSize(String value) {
        this.headSize = value;
    }

    /**
     * Gets the value of the headWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadWidth() {
        return headWidth;
    }

    /**
     * Sets the value of the headWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadWidth(String value) {
        this.headWidth = value;
    }

    /**
     * Gets the value of the ignoreWarnings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIgnoreWarnings() {
        if (ignoreWarnings == null) {
            return "no";
        } else {
            return ignoreWarnings;
        }
    }

    /**
     * Sets the value of the ignoreWarnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIgnoreWarnings(String value) {
        this.ignoreWarnings = value;
    }

    /**
     * Gets the value of the lineType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineType() {
        return lineType;
    }

    /**
     * Sets the value of the lineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineType(String value) {
        this.lineType = value;
    }

    /**
     * Gets the value of the lineWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineWidth() {
        return lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineWidth(String value) {
        this.lineWidth = value;
    }

    /**
     * Gets the value of the supersededBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupersededBy() {
        return supersededBy;
    }

    /**
     * Sets the value of the supersededBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupersededBy(String value) {
        this.supersededBy = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisible() {
        if (visible == null) {
            return "yes";
        } else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisible(String value) {
        this.visible = value;
    }

    /**
     * Gets the value of the warning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarning() {
        return warning;
    }

    /**
     * Sets the value of the warning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarning(String value) {
        this.warning = value;
    }

    /**
     * Gets the value of the z property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZ() {
        return z;
    }

    /**
     * Sets the value of the z property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZ(String value) {
        this.z = value;
    }

    /**
     * Gets the value of the bgRGBA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBgRGBA() {
        return bgRGBA;
    }

    /**
     * Sets the value of the bgRGBA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBgRGBA(String value) {
        this.bgRGBA = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the fgRGBA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFgRGBA() {
        return fgRGBA;
    }

    /**
     * Sets the value of the fgRGBA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFgRGBA(String value) {
        this.fgRGBA = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
