//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.03 at 09:18:46 AM ACT 
//


package translator.cdxml.dom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}t"/>
 *         &lt;element ref="{}fragment"/>
 *         &lt;element ref="{}group"/>
 *         &lt;element ref="{}graphic"/>
 *         &lt;element ref="{}altgroup"/>
 *         &lt;element ref="{}curve"/>
 *         &lt;element ref="{}step"/>
 *         &lt;element ref="{}scheme"/>
 *         &lt;element ref="{}spectrum"/>
 *         &lt;element ref="{}objecttag"/>
 *         &lt;element ref="{}annotation"/>
 *         &lt;element ref="{}plasmidmap"/>
 *         &lt;element ref="{}rlogic"/>
 *         &lt;element ref="{}arrow"/>
 *         &lt;element ref="{}bioshape"/>
 *       &lt;/choice>
 *       &lt;attribute name="BoundingBox" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Integral" default="no">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tOrFragmentOrGroup"
})
@XmlRootElement(name = "group")
public class Group {

    @XmlElements({
        @XmlElement(name = "altgroup", type = Altgroup.class),
        @XmlElement(name = "arrow", type = Arrow.class),
        @XmlElement(name = "curve", type = Curve.class),
        @XmlElement(name = "spectrum", type = Spectrum.class),
        @XmlElement(name = "graphic", type = Graphic.class),
        @XmlElement(name = "plasmidmap", type = Plasmidmap.class),
        @XmlElement(name = "t", type = T.class),
        @XmlElement(name = "objecttag", type = Objecttag.class),
        @XmlElement(name = "annotation", type = Annotation.class),
        @XmlElement(name = "scheme", type = Scheme.class),
        @XmlElement(name = "step", type = Step.class),
        @XmlElement(name = "rlogic", type = Rlogic.class),
        @XmlElement(name = "fragment", type = Fragment.class),
        @XmlElement(name = "bioshape", type = Bioshape.class),
        @XmlElement(name = "group", type = Group.class)
    })
    protected List<Object> tOrFragmentOrGroup;
    @XmlAttribute(name = "BoundingBox")
    protected String boundingBox;
    @XmlAttribute(name = "Integral")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String integral;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the tOrFragmentOrGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tOrFragmentOrGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTOrFragmentOrGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Altgroup }
     * {@link Arrow }
     * {@link Curve }
     * {@link Spectrum }
     * {@link Graphic }
     * {@link Plasmidmap }
     * {@link T }
     * {@link Objecttag }
     * {@link Annotation }
     * {@link Scheme }
     * {@link Step }
     * {@link Rlogic }
     * {@link Fragment }
     * {@link Bioshape }
     * {@link Group }
     * 
     * 
     */
    public List<Object> getTOrFragmentOrGroup() {
        if (tOrFragmentOrGroup == null) {
            tOrFragmentOrGroup = new ArrayList<Object>();
        }
        return this.tOrFragmentOrGroup;
    }

    /**
     * Gets the value of the boundingBox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoundingBox() {
        return boundingBox;
    }

    /**
     * Sets the value of the boundingBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoundingBox(String value) {
        this.boundingBox = value;
    }

    /**
     * Gets the value of the integral property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntegral() {
        if (integral == null) {
            return "no";
        } else {
            return integral;
        }
    }

    /**
     * Sets the value of the integral property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntegral(String value) {
        this.integral = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
