//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.03 at 09:18:46 AM ACT 
//


package translator.cdxml.dom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}t"/>
 *         &lt;element ref="{}fragment"/>
 *         &lt;element ref="{}group"/>
 *         &lt;element ref="{}graphic"/>
 *         &lt;element ref="{}altgroup"/>
 *         &lt;element ref="{}curve"/>
 *         &lt;element ref="{}step"/>
 *         &lt;element ref="{}scheme"/>
 *         &lt;element ref="{}spectrum"/>
 *         &lt;element ref="{}embeddedobject"/>
 *         &lt;element ref="{}sequence"/>
 *         &lt;element ref="{}crossreference"/>
 *         &lt;element ref="{}splitter"/>
 *         &lt;element ref="{}table"/>
 *         &lt;element ref="{}bracketedgroup"/>
 *         &lt;element ref="{}border"/>
 *         &lt;element ref="{}geometry"/>
 *         &lt;element ref="{}constraint"/>
 *         &lt;element ref="{}tlcplate"/>
 *         &lt;element ref="{}chemicalproperty"/>
 *         &lt;element ref="{}arrow"/>
 *         &lt;element ref="{}bioshape"/>
 *         &lt;element ref="{}stoichiometrygrid"/>
 *         &lt;element ref="{}plasmidmap"/>
 *         &lt;element ref="{}objecttag"/>
 *         &lt;element ref="{}annotation"/>
 *         &lt;element ref="{}rlogic"/>
 *       &lt;/choice>
 *       &lt;attribute name="BoundingBox" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BoundsInParent" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="DrawingSpace" default="pages">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="poster"/>
 *             &lt;enumeration value="pages"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Footer" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FooterPosition" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Header" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HeaderPosition" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Height" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HeightPages" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="1" />
 *       &lt;attribute name="PageDefinition" default="Undefined">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Undefined"/>
 *             &lt;enumeration value="Center"/>
 *             &lt;enumeration value="TL4"/>
 *             &lt;enumeration value="IDTerm"/>
 *             &lt;enumeration value="FlushLeft"/>
 *             &lt;enumeration value="FlushRight"/>
 *             &lt;enumeration value="Reaction1"/>
 *             &lt;enumeration value="Reaction2"/>
 *             &lt;enumeration value="MulticolumnTL4"/>
 *             &lt;enumeration value="MulticolumnNonTL4"/>
 *             &lt;enumeration value="UserDefined"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="PageOverlap" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PrintTrimMarks" default="no">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SplitterPositions" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Width" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="WidthPages" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="1" />
 *       &lt;attribute name="bgRGBA" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="bgcolor" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="fgRGBA" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tOrFragmentOrGroup"
})
@XmlRootElement(name = "page")
public class Page {

    @XmlElements({
        @XmlElement(name = "tlcplate", type = Tlcplate.class),
        @XmlElement(name = "spectrum", type = Spectrum.class),
        @XmlElement(name = "annotation", type = Annotation.class),
        @XmlElement(name = "constraint", type = Constraint.class),
        @XmlElement(name = "splitter", type = Splitter.class),
        @XmlElement(name = "graphic", type = Graphic.class),
        @XmlElement(name = "crossreference", type = Crossreference.class),
        @XmlElement(name = "chemicalproperty", type = Chemicalproperty.class),
        @XmlElement(name = "scheme", type = Scheme.class),
        @XmlElement(name = "plasmidmap", type = Plasmidmap.class),
        @XmlElement(name = "altgroup", type = Altgroup.class),
        @XmlElement(name = "bracketedgroup", type = Bracketedgroup.class),
        @XmlElement(name = "fragment", type = Fragment.class),
        @XmlElement(name = "step", type = Step.class),
        @XmlElement(name = "stoichiometrygrid", type = Stoichiometrygrid.class),
        @XmlElement(name = "arrow", type = Arrow.class),
        @XmlElement(name = "sequence", type = Sequence.class),
        @XmlElement(name = "border", type = Border.class),
        @XmlElement(name = "embeddedobject", type = Embeddedobject.class),
        @XmlElement(name = "group", type = Group.class),
        @XmlElement(name = "objecttag", type = Objecttag.class),
        @XmlElement(name = "curve", type = Curve.class),
        @XmlElement(name = "bioshape", type = Bioshape.class),
        @XmlElement(name = "geometry", type = Geometry.class),
        @XmlElement(name = "t", type = T.class),
        @XmlElement(name = "table", type = Table.class),
        @XmlElement(name = "rlogic", type = Rlogic.class)
    })
    protected List<Object> tOrFragmentOrGroup;
    @XmlAttribute(name = "BoundingBox")
    protected String boundingBox;
    @XmlAttribute(name = "BoundsInParent")
    protected String boundsInParent;
    @XmlAttribute(name = "DrawingSpace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String drawingSpace;
    @XmlAttribute(name = "Footer")
    protected String footer;
    @XmlAttribute(name = "FooterPosition")
    protected String footerPosition;
    @XmlAttribute(name = "Header")
    protected String header;
    @XmlAttribute(name = "HeaderPosition")
    protected String headerPosition;
    @XmlAttribute(name = "Height")
    protected String height;
    @XmlAttribute(name = "HeightPages")
    protected String heightPages;
    @XmlAttribute(name = "PageDefinition")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String pageDefinition;
    @XmlAttribute(name = "PageOverlap")
    protected String pageOverlap;
    @XmlAttribute(name = "PrintTrimMarks")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String printTrimMarks;
    @XmlAttribute(name = "SplitterPositions")
    protected String splitterPositions;
    @XmlAttribute(name = "Width")
    protected String width;
    @XmlAttribute(name = "WidthPages")
    protected String widthPages;
    @XmlAttribute
    protected String bgRGBA;
    @XmlAttribute
    protected String bgcolor;
    @XmlAttribute
    protected String color;
    @XmlAttribute
    protected String fgRGBA;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the tOrFragmentOrGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tOrFragmentOrGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTOrFragmentOrGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tlcplate }
     * {@link Spectrum }
     * {@link Annotation }
     * {@link Constraint }
     * {@link Splitter }
     * {@link Graphic }
     * {@link Crossreference }
     * {@link Chemicalproperty }
     * {@link Scheme }
     * {@link Plasmidmap }
     * {@link Altgroup }
     * {@link Bracketedgroup }
     * {@link Fragment }
     * {@link Step }
     * {@link Stoichiometrygrid }
     * {@link Arrow }
     * {@link Sequence }
     * {@link Border }
     * {@link Embeddedobject }
     * {@link Group }
     * {@link Objecttag }
     * {@link Curve }
     * {@link Bioshape }
     * {@link Geometry }
     * {@link T }
     * {@link Table }
     * {@link Rlogic }
     * 
     * 
     */
    public List<Object> getTOrFragmentOrGroup() {
        if (tOrFragmentOrGroup == null) {
            tOrFragmentOrGroup = new ArrayList<Object>();
        }
        return this.tOrFragmentOrGroup;
    }

    /**
     * Gets the value of the boundingBox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoundingBox() {
        return boundingBox;
    }

    /**
     * Sets the value of the boundingBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoundingBox(String value) {
        this.boundingBox = value;
    }

    /**
     * Gets the value of the boundsInParent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoundsInParent() {
        return boundsInParent;
    }

    /**
     * Sets the value of the boundsInParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoundsInParent(String value) {
        this.boundsInParent = value;
    }

    /**
     * Gets the value of the drawingSpace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawingSpace() {
        if (drawingSpace == null) {
            return "pages";
        } else {
            return drawingSpace;
        }
    }

    /**
     * Sets the value of the drawingSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawingSpace(String value) {
        this.drawingSpace = value;
    }

    /**
     * Gets the value of the footer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFooter() {
        return footer;
    }

    /**
     * Sets the value of the footer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFooter(String value) {
        this.footer = value;
    }

    /**
     * Gets the value of the footerPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFooterPosition() {
        return footerPosition;
    }

    /**
     * Sets the value of the footerPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFooterPosition(String value) {
        this.footerPosition = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeader(String value) {
        this.header = value;
    }

    /**
     * Gets the value of the headerPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeaderPosition() {
        return headerPosition;
    }

    /**
     * Sets the value of the headerPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeaderPosition(String value) {
        this.headerPosition = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the heightPages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeightPages() {
        if (heightPages == null) {
            return "1";
        } else {
            return heightPages;
        }
    }

    /**
     * Sets the value of the heightPages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeightPages(String value) {
        this.heightPages = value;
    }

    /**
     * Gets the value of the pageDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageDefinition() {
        if (pageDefinition == null) {
            return "Undefined";
        } else {
            return pageDefinition;
        }
    }

    /**
     * Sets the value of the pageDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageDefinition(String value) {
        this.pageDefinition = value;
    }

    /**
     * Gets the value of the pageOverlap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageOverlap() {
        return pageOverlap;
    }

    /**
     * Sets the value of the pageOverlap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageOverlap(String value) {
        this.pageOverlap = value;
    }

    /**
     * Gets the value of the printTrimMarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintTrimMarks() {
        if (printTrimMarks == null) {
            return "no";
        } else {
            return printTrimMarks;
        }
    }

    /**
     * Sets the value of the printTrimMarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintTrimMarks(String value) {
        this.printTrimMarks = value;
    }

    /**
     * Gets the value of the splitterPositions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSplitterPositions() {
        return splitterPositions;
    }

    /**
     * Sets the value of the splitterPositions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSplitterPositions(String value) {
        this.splitterPositions = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the widthPages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidthPages() {
        if (widthPages == null) {
            return "1";
        } else {
            return widthPages;
        }
    }

    /**
     * Sets the value of the widthPages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidthPages(String value) {
        this.widthPages = value;
    }

    /**
     * Gets the value of the bgRGBA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBgRGBA() {
        return bgRGBA;
    }

    /**
     * Sets the value of the bgRGBA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBgRGBA(String value) {
        this.bgRGBA = value;
    }

    /**
     * Gets the value of the bgcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBgcolor() {
        return bgcolor;
    }

    /**
     * Sets the value of the bgcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBgcolor(String value) {
        this.bgcolor = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the fgRGBA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFgRGBA() {
        return fgRGBA;
    }

    /**
     * Sets the value of the fgRGBA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFgRGBA(String value) {
        this.fgRGBA = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
