//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.03 at 09:18:46 AM ACT 
//


package translator.cdxml.dom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}objecttag"/>
 *         &lt;element ref="{}annotation"/>
 *       &lt;/choice>
 *       &lt;attribute name="AngularSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ArrowShaftSpacing" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ArrowheadCenterSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ArrowheadHead">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Unspecified"/>
 *             &lt;enumeration value="None"/>
 *             &lt;enumeration value="Full"/>
 *             &lt;enumeration value="HalfLeft"/>
 *             &lt;enumeration value="HalfRight"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ArrowheadTail">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Unspecified"/>
 *             &lt;enumeration value="None"/>
 *             &lt;enumeration value="Full"/>
 *             &lt;enumeration value="HalfLeft"/>
 *             &lt;enumeration value="HalfRight"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ArrowheadType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Solid"/>
 *             &lt;enumeration value="Hollow"/>
 *             &lt;enumeration value="Angle"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ArrowheadWidth" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BoundingBox" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Center3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FadePercent" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FillType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Unspecified"/>
 *             &lt;enumeration value="None"/>
 *             &lt;enumeration value="Solid"/>
 *             &lt;enumeration value="Shaded"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Head3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HeadSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="LineType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Solid"/>
 *             &lt;enumeration value="Dashed"/>
 *             &lt;enumeration value="Bold"/>
 *             &lt;enumeration value="Wavy"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="MajorAxisEnd3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="MinorAxisEnd3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RegionEnd" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RegionOffset" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RegionStart" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Tail3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="bgRGBA" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="fgRGBA" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objecttagOrAnnotation"
})
@XmlRootElement(name = "plasmidregion")
public class Plasmidregion {

    @XmlElements({
        @XmlElement(name = "annotation", type = Annotation.class),
        @XmlElement(name = "objecttag", type = Objecttag.class)
    })
    protected List<Object> objecttagOrAnnotation;
    @XmlAttribute(name = "AngularSize")
    protected String angularSize;
    @XmlAttribute(name = "ArrowShaftSpacing")
    protected String arrowShaftSpacing;
    @XmlAttribute(name = "ArrowheadCenterSize")
    protected String arrowheadCenterSize;
    @XmlAttribute(name = "ArrowheadHead")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String arrowheadHead;
    @XmlAttribute(name = "ArrowheadTail")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String arrowheadTail;
    @XmlAttribute(name = "ArrowheadType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String arrowheadType;
    @XmlAttribute(name = "ArrowheadWidth")
    protected String arrowheadWidth;
    @XmlAttribute(name = "BoundingBox")
    protected String boundingBox;
    @XmlAttribute(name = "Center3D")
    protected String center3D;
    @XmlAttribute(name = "FadePercent")
    protected String fadePercent;
    @XmlAttribute(name = "FillType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fillType;
    @XmlAttribute(name = "Head3D")
    protected String head3D;
    @XmlAttribute(name = "HeadSize")
    protected String headSize;
    @XmlAttribute(name = "LineType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lineType;
    @XmlAttribute(name = "MajorAxisEnd3D")
    protected String majorAxisEnd3D;
    @XmlAttribute(name = "MinorAxisEnd3D")
    protected String minorAxisEnd3D;
    @XmlAttribute(name = "RegionEnd")
    protected String regionEnd;
    @XmlAttribute(name = "RegionOffset")
    protected String regionOffset;
    @XmlAttribute(name = "RegionStart")
    protected String regionStart;
    @XmlAttribute(name = "Tail3D")
    protected String tail3D;
    @XmlAttribute(name = "Z")
    protected String z;
    @XmlAttribute
    protected String bgRGBA;
    @XmlAttribute
    protected String color;
    @XmlAttribute
    protected String fgRGBA;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the objecttagOrAnnotation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objecttagOrAnnotation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjecttagOrAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Annotation }
     * {@link Objecttag }
     * 
     * 
     */
    public List<Object> getObjecttagOrAnnotation() {
        if (objecttagOrAnnotation == null) {
            objecttagOrAnnotation = new ArrayList<Object>();
        }
        return this.objecttagOrAnnotation;
    }

    /**
     * Gets the value of the angularSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAngularSize() {
        return angularSize;
    }

    /**
     * Sets the value of the angularSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAngularSize(String value) {
        this.angularSize = value;
    }

    /**
     * Gets the value of the arrowShaftSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowShaftSpacing() {
        return arrowShaftSpacing;
    }

    /**
     * Sets the value of the arrowShaftSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowShaftSpacing(String value) {
        this.arrowShaftSpacing = value;
    }

    /**
     * Gets the value of the arrowheadCenterSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowheadCenterSize() {
        return arrowheadCenterSize;
    }

    /**
     * Sets the value of the arrowheadCenterSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowheadCenterSize(String value) {
        this.arrowheadCenterSize = value;
    }

    /**
     * Gets the value of the arrowheadHead property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowheadHead() {
        return arrowheadHead;
    }

    /**
     * Sets the value of the arrowheadHead property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowheadHead(String value) {
        this.arrowheadHead = value;
    }

    /**
     * Gets the value of the arrowheadTail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowheadTail() {
        return arrowheadTail;
    }

    /**
     * Sets the value of the arrowheadTail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowheadTail(String value) {
        this.arrowheadTail = value;
    }

    /**
     * Gets the value of the arrowheadType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowheadType() {
        return arrowheadType;
    }

    /**
     * Sets the value of the arrowheadType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowheadType(String value) {
        this.arrowheadType = value;
    }

    /**
     * Gets the value of the arrowheadWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowheadWidth() {
        return arrowheadWidth;
    }

    /**
     * Sets the value of the arrowheadWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowheadWidth(String value) {
        this.arrowheadWidth = value;
    }

    /**
     * Gets the value of the boundingBox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoundingBox() {
        return boundingBox;
    }

    /**
     * Sets the value of the boundingBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoundingBox(String value) {
        this.boundingBox = value;
    }

    /**
     * Gets the value of the center3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCenter3D() {
        return center3D;
    }

    /**
     * Sets the value of the center3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCenter3D(String value) {
        this.center3D = value;
    }

    /**
     * Gets the value of the fadePercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFadePercent() {
        return fadePercent;
    }

    /**
     * Sets the value of the fadePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFadePercent(String value) {
        this.fadePercent = value;
    }

    /**
     * Gets the value of the fillType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillType() {
        return fillType;
    }

    /**
     * Sets the value of the fillType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillType(String value) {
        this.fillType = value;
    }

    /**
     * Gets the value of the head3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHead3D() {
        return head3D;
    }

    /**
     * Sets the value of the head3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHead3D(String value) {
        this.head3D = value;
    }

    /**
     * Gets the value of the headSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadSize() {
        return headSize;
    }

    /**
     * Sets the value of the headSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadSize(String value) {
        this.headSize = value;
    }

    /**
     * Gets the value of the lineType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineType() {
        return lineType;
    }

    /**
     * Sets the value of the lineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineType(String value) {
        this.lineType = value;
    }

    /**
     * Gets the value of the majorAxisEnd3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMajorAxisEnd3D() {
        return majorAxisEnd3D;
    }

    /**
     * Sets the value of the majorAxisEnd3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMajorAxisEnd3D(String value) {
        this.majorAxisEnd3D = value;
    }

    /**
     * Gets the value of the minorAxisEnd3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinorAxisEnd3D() {
        return minorAxisEnd3D;
    }

    /**
     * Sets the value of the minorAxisEnd3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinorAxisEnd3D(String value) {
        this.minorAxisEnd3D = value;
    }

    /**
     * Gets the value of the regionEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionEnd() {
        return regionEnd;
    }

    /**
     * Sets the value of the regionEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionEnd(String value) {
        this.regionEnd = value;
    }

    /**
     * Gets the value of the regionOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionOffset() {
        return regionOffset;
    }

    /**
     * Sets the value of the regionOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionOffset(String value) {
        this.regionOffset = value;
    }

    /**
     * Gets the value of the regionStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionStart() {
        return regionStart;
    }

    /**
     * Sets the value of the regionStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionStart(String value) {
        this.regionStart = value;
    }

    /**
     * Gets the value of the tail3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTail3D() {
        return tail3D;
    }

    /**
     * Sets the value of the tail3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTail3D(String value) {
        this.tail3D = value;
    }

    /**
     * Gets the value of the z property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZ() {
        return z;
    }

    /**
     * Sets the value of the z property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZ(String value) {
        this.z = value;
    }

    /**
     * Gets the value of the bgRGBA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBgRGBA() {
        return bgRGBA;
    }

    /**
     * Sets the value of the bgRGBA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBgRGBA(String value) {
        this.bgRGBA = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the fgRGBA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFgRGBA() {
        return fgRGBA;
    }

    /**
     * Sets the value of the fgRGBA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFgRGBA(String value) {
        this.fgRGBA = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
