//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.03 at 09:18:46 AM ACT 
//


package translator.cdxml.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="RLogicGroup" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RLogicIfThenGroup" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RLogicOccurrence" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RLogicRestH" default="no">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "rlogicitem")
public class Rlogicitem {

    @XmlAttribute(name = "RLogicGroup")
    protected String rLogicGroup;
    @XmlAttribute(name = "RLogicIfThenGroup")
    protected String rLogicIfThenGroup;
    @XmlAttribute(name = "RLogicOccurrence")
    protected String rLogicOccurrence;
    @XmlAttribute(name = "RLogicRestH")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rLogicRestH;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the rLogicGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRLogicGroup() {
        return rLogicGroup;
    }

    /**
     * Sets the value of the rLogicGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRLogicGroup(String value) {
        this.rLogicGroup = value;
    }

    /**
     * Gets the value of the rLogicIfThenGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRLogicIfThenGroup() {
        return rLogicIfThenGroup;
    }

    /**
     * Sets the value of the rLogicIfThenGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRLogicIfThenGroup(String value) {
        this.rLogicIfThenGroup = value;
    }

    /**
     * Gets the value of the rLogicOccurrence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRLogicOccurrence() {
        return rLogicOccurrence;
    }

    /**
     * Sets the value of the rLogicOccurrence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRLogicOccurrence(String value) {
        this.rLogicOccurrence = value;
    }

    /**
     * Gets the value of the rLogicRestH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRLogicRestH() {
        if (rLogicRestH == null) {
            return "no";
        } else {
            return rLogicRestH;
        }
    }

    /**
     * Sets the value of the rLogicRestH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRLogicRestH(String value) {
        this.rLogicRestH = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
