//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.03 at 09:18:46 AM ACT 
//


package translator.cdxml.dom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}objecttag"/>
 *         &lt;element ref="{}embeddedobject"/>
 *       &lt;/choice>
 *       &lt;attribute name="IsEdited" default="no">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="IsHidden" default="no">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="IsReadOnly" default="no">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SGDataType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SGDataValue" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SGPropertyType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Visible" default="yes">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objecttagOrEmbeddedobject"
})
@XmlRootElement(name = "sgdatum")
public class Sgdatum {

    @XmlElements({
        @XmlElement(name = "embeddedobject", type = Embeddedobject.class),
        @XmlElement(name = "objecttag", type = Objecttag.class)
    })
    protected List<Object> objecttagOrEmbeddedobject;
    @XmlAttribute(name = "IsEdited")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isEdited;
    @XmlAttribute(name = "IsHidden")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isHidden;
    @XmlAttribute(name = "IsReadOnly")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isReadOnly;
    @XmlAttribute(name = "SGDataType")
    protected String sgDataType;
    @XmlAttribute(name = "SGDataValue")
    protected String sgDataValue;
    @XmlAttribute(name = "SGPropertyType")
    protected String sgPropertyType;
    @XmlAttribute(name = "Visible")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String visible;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the objecttagOrEmbeddedobject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objecttagOrEmbeddedobject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjecttagOrEmbeddedobject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Embeddedobject }
     * {@link Objecttag }
     * 
     * 
     */
    public List<Object> getObjecttagOrEmbeddedobject() {
        if (objecttagOrEmbeddedobject == null) {
            objecttagOrEmbeddedobject = new ArrayList<Object>();
        }
        return this.objecttagOrEmbeddedobject;
    }

    /**
     * Gets the value of the isEdited property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsEdited() {
        if (isEdited == null) {
            return "no";
        } else {
            return isEdited;
        }
    }

    /**
     * Sets the value of the isEdited property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEdited(String value) {
        this.isEdited = value;
    }

    /**
     * Gets the value of the isHidden property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsHidden() {
        if (isHidden == null) {
            return "no";
        } else {
            return isHidden;
        }
    }

    /**
     * Sets the value of the isHidden property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsHidden(String value) {
        this.isHidden = value;
    }

    /**
     * Gets the value of the isReadOnly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsReadOnly() {
        if (isReadOnly == null) {
            return "no";
        } else {
            return isReadOnly;
        }
    }

    /**
     * Sets the value of the isReadOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsReadOnly(String value) {
        this.isReadOnly = value;
    }

    /**
     * Gets the value of the sgDataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSGDataType() {
        return sgDataType;
    }

    /**
     * Sets the value of the sgDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSGDataType(String value) {
        this.sgDataType = value;
    }

    /**
     * Gets the value of the sgDataValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSGDataValue() {
        return sgDataValue;
    }

    /**
     * Sets the value of the sgDataValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSGDataValue(String value) {
        this.sgDataValue = value;
    }

    /**
     * Gets the value of the sgPropertyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSGPropertyType() {
        return sgPropertyType;
    }

    /**
     * Sets the value of the sgPropertyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSGPropertyType(String value) {
        this.sgPropertyType = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisible() {
        if (visible == null) {
            return "yes";
        } else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisible(String value) {
        this.visible = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
