//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.15 at 02:23:31 PM ACT 
//


package translator.domains.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for document-preferences complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="document-preferences">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="shadowRatio" type="{http://www.w3.org/2001/XMLSchema}int" default="25" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "document-preferences")
public class DocumentPreferences {

    @XmlAttribute
    protected String shadowRatio;

    /**
     * Gets the value of the shadowRatio property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public String getShadowRatio() {
        if (shadowRatio == null) {
            return  "25";
        } else {
            return shadowRatio;
        }
    }

    /**
     * Sets the value of the shadowRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setShadowRatio(String value) {
        this.shadowRatio = value;
    }

}
