/*
 * SVGViewer.java
 *
 * Created on July 23, 2007, 1:09 PM
 */

package svgrenderer.viewer;

import java.awt.Cursor;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import org.apache.batik.swing.JSVGCanvas;

/**
 *
 * @author  aceccoli
 */
public class SVGViewer extends javax.swing.JApplet {
    
    public SVGViewer() {
        initComponents();
        canvas.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("F7"), JSVGCanvas.ZOOM_IN_ACTION);
        canvas.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("F8"), JSVGCanvas.ZOOM_OUT_ACTION);
        canvas.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("F6"), JSVGCanvas.RESET_TRANSFORM_ACTION);
    }
    
    /** Initializes the applet SVGViewer */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    try {
                        URL svgProvider = new URL(getCodeBase(), getParameter("svgpath"));
                        canvas.setURI(svgProvider.toString());
                    } catch (MalformedURLException ex) {
                        ex.printStackTrace();
                    }
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        content = new javax.swing.JPanel();
        canvas = new org.apache.batik.swing.JSVGCanvas();

        scroll = new org.apache.batik.swing.JSVGScrollPane(canvas);

        content.setLayout(new java.awt.BorderLayout());

        content.add(scroll, java.awt.BorderLayout.CENTER);

        getContentPane().add(content, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.apache.batik.swing.JSVGCanvas canvas;
    private org.apache.batik.swing.JSVGScrollPane scroll;
    private javax.swing.JPanel content;
    // End of variables declaration//GEN-END:variables
    
}
